[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
prompt = "masking"

[tool.poetry]
name = "masking"
version = "0.1.0"
description = "Python package for the masking of Personal Identifiable Information (PII) data consisting of a table."
authors = ["Marco Petrella <marco.petrella@d-one.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.8"
pre-commit = "^3.7.1"

###################### Ruff ######################

[tool.ruff]
preview = true
target-version = "py311"

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.ruff.lint]
dummy-variable-rgx = "^_$"
ignore = [
    "CPY001",  # flake8-copyright
    "D1",      # undocumented-*
    "D203",    # one-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "E501",    # line-too-long
    "S608",    # hardcoded-sql-expression
    "BLE001",  # catch-blind-exceptions
    "COM812",  # missing-trailing-commas
]
select = ["ALL"]
